# This is a YAML-formatted file.
# - declares variables to be passed into your templates
# - provides default values where applicable

hull:
  config:
    general:
      debug:
        renderBrokenHullGetTransformationReferences: true
      fullnameOverride: cardvalidation
      data:
        installation:
          config:
            certificateSecrets: {}
    specific:
      tag: "7-b797d86"
      components:
        cardvalidation:
          mounts:
            configmap:
              appsettings.json:
                Logging:
                  LogLevel:
                    Default: "Information"
                    Microsoft.AspNetCore: "Warning"
                AllowedHosts: "*"
                EnableSwagger: true

  objects:
    registry:
      ghr:
        server: ghcr.io
        username: ""
        password: ""
    service:
      _HULL_OBJECT_TYPE_DEFAULT_:
        type: ClusterIP
        ports:
          http:
            port: 8080
            targetPort: http  
      cardvalidation: {}
     
    secret:
      _HULL_OBJECT_TYPE_DEFAULT_:
        annotations:
          helm.sh/hook: pre-install,pre-upgrade
          helm.sh/hook-delete-policy: before-hook-creation
          helm.sh/hook-weight: "-80"

    configmap:  
      _HULL_OBJECT_TYPE_DEFAULT_:
        annotations:
          helm.sh/hook: pre-install,pre-upgrade
          helm.sh/hook-delete-policy: before-hook-creation
          helm.sh/hook-weight: "-80"
      cardvalidation:
        data: _HT/hull.vidispine.addon.library.component.configmap.data:COMPONENT:"cardvalidation"
          # mapKey:
          #   inline: ""
    
    deployment:
      # Configure defaults for the deployments if needed
      _HULL_OBJECT_TYPE_DEFAULT_:
        annotations:
          helm.sh/hook-delete-policy: before-hook-creation
        pod:
          volumes:
            certs:
              enabled: false
            etcssl:
              enabled: false
          containers:
            _HULL_OBJECT_TYPE_DEFAULT_:
              ports:
                http:
                  containerPort: 8080
                  protocol: TCP
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 200m
                  memory: 512Mi
              livenessProbe:
                httpGet:
                  path: /_health
                  port: http
                initialDelaySeconds: 60
                failureThreshold: 20
                successThreshold: 1
                periodSeconds: 30
                timeoutSeconds: 20
              readinessProbe:
                httpGet:
                  path: /_health
                  port: http
                initialDelaySeconds: 30
                successThreshold: 1
                failureThreshold: 4
                periodSeconds: 15
                timeoutSeconds: 20
              volumeMounts:
                etcssl:
                  enabled: false
                certs:
                  enabled: false
      cardvalidation:
        pod:
          containers:
            cardvalidation:
              image:
                repository: ghcr.io/dksx/validatecard
                tag: _HT*hull.config.specific.tag
              volumeMounts:
                appsettings:
                  name: appsettings
                  mountPath: 'app/config/appsettings.json'
                  subPath: appsettings.json
          volumes:
            appsettings:
              configMap:
                name: "cardvalidation"
                defaultMode: 0744
    job:
      _HULL_OBJECT_TYPE_DEFAULT_:
        enabled: false
        annotations:
          helm.sh/hook: pre-install,pre-upgrade
          helm.sh/hook-delete-policy: before-hook-creation
          helm.sh/hook-weight: "-10"
        backoffLimit: 4
    ingress:
      _HULL_OBJECT_TYPE_DEFAULT_:
        enabled: false
        